name: E2E

on:
  pull_request:
    branches: [master]

jobs:
  ubuntu-latest:
    name: Ubuntu 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npx serve -s build -l 3000
          wait-on: 'http://localhost:3000'
